version: '3.6'
services:
    dev:
        container_name: wygryzanko_poc
        stdin_open: true
        tty: true
        ports:
            - '31337:31337'
            - '4200:4200'
            - '4201:4201'
        volumes:
            - type: "bind"
              source: ./
              target: /home/poc/project
            - type: "volume"
              source: ng_modules_poc
              target: /home/poc/project/frontend/node_modules
            - type: "volume"
              source: ng_modules_poc_back
              target: /home/poc/project/backend/node_modules
        restart: always
        logging:
            options:
                max-size: 1g
        build:
          context: ./
          dockerfile: Dockerfile
          target: 'development'
        depends_on: 
          - mongo
        networks:
          default:
    mongo:
      container_name: mongo_poc
      ports:
        - '27017:27017'
      image: mongo:4.1.5
      volumes:
        - type: "volume"
          source: mongo_data
          target: /data/db
volumes:
  ng_modules_poc:
  ng_modules_poc_back:
  mongo_data:
networks:
  default:

